springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8081

spring:
  config:
    import: classpath:secret.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_schema: next_chat

jwt:
  access:
    secret: ser6g5WEQrEfgg4h8sth4IHI5634eeg5se5EWFT234EG7ETRWer4t
    expiration: 300000
  refresh:
    secret: dtJ45fju123445YRJPKJ6745wrtge53123JBf4D6HHJfgoEgtydS
    expiration: 604920000